source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'pg'
gem 'decent_exposure'
gem 'haml-rails'
gem 'compass'
gem 'html5-boilerplate'
gem 'dynamic_form'
gem 'newrelic_rpm'

group :development, :test do
  gem 'capybara', '~> 0.4'
  gem 'cucumber'
  gem 'cucumber-rails', '0.4.1'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'faker'
  gem 'launchy'
  gem 'rspec', '2.0.1'
  gem 'rspec-rails', '2.0.1'
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'shoulda'
  gem 'watchr'
  gem 'sqlite3'
end
