development:
  adapter: sqlite3
  database: db/byus_dev.sqlite3
test: &test
  adapter: sqlite3
  database: db/byus_test.sqlite3
production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: byus_production
  pool: 5
  username: root
  password:

cucumber:
  <<: *test
